{% set name = "pyflwdir" %}
{% set version = "0.5.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflwdir-{{ version }}.tar.gz
  sha256: be059dcade8bde51102e7e832903e76bec391b8bb460ca571895f511f4c18e4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.9
  run:
    - affine
    - numba >=0.54
    - numpy
    - python >=3.9
    - scipy

test:
  imports:
    - pyflwdir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deltares/pyflwdir/
  summary: Fast methods to work with hydro- and topography data in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - DirkEilander
