{% set name = "pyflwdir" %}
{% set version = "0.5.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyflwdir-{{ version }}.tar.gz
  sha256: 499499b36117e202ebac6388026cb7c972128a1bbc943ac84f73656524e567f0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
  run:
    - affine
    - numba >=0.54,<1.0
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - pyflwdir
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deltares/pyflwdir/
  summary: Fast methods to work with hydro- and topography data in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deltares-service-account
    - DirkEilander
